### PR TITLE
Jamie/uncover code of conduct

### PR DESCRIPTION
**Pull request by thejamielin**
- removed the leaf from the code of conduct

### CODE REVIEW

**Comment by thejamielin** [comment]
Does the header look weird? Should we center it?

**Review by zefwang — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
please rebase your branch on main and then force push, you have some extra commits here

**Comment by thejamielin** [comment]
> please rebase your branch on main and then force push, you have some extra commits here

fixed!

**Review by jessicasu77 — APPROVED** [review]
lgtm!

**Review by ghost — APPROVED** [review]

**Pull request merged**
